// Scene geometry as lists of faces. Pure: every function returns
// {pts:[worldPoint...], fill, alpha} and touches no canvas.
//
// Shading is crude on purpose -- a fixed brightness per face orientation, no
// light model. It is enough to read shape from, and a real one would be the
// first step towards carrying a 3D engine for a scene that is a grid, some
// cylinders and a drone.

import { add, quatMat, rotate } from "./vec3.js";

/// Multiply a #rrggbb hex colour by k, clamped. k > 1 brightens.
export function shadeHex(hex, k) {
  const n = parseInt(hex.slice(1), 16);
  const ch = (shift) => Math.min(255, Math.round(((n >> shift) & 255) * k));
  return `rgb(${ch(16)},${ch(8)},${ch(0)})`;
}

const QUADS = [[0, 1, 2, 3], [4, 5, 6, 7], [0, 1, 5, 4],
               [1, 2, 6, 5], [2, 3, 7, 6], [3, 0, 4, 7]];
const QUAD_SHADE = [0.55, 1.0, 0.78, 0.68, 0.78, 0.68];

function boxCorners(hx, hy, hz) {
  return [
    [-hx, -hy, -hz], [hx, -hy, -hz], [hx, hy, -hz], [-hx, hy, -hz],
    [-hx, -hy, hz], [hx, -hy, hz], [hx, hy, hz], [-hx, hy, hz],
  ];
}

export function boxFaces(cx, cy, cz, sx, sy, sz, fill) {
  const v = boxCorners(sx / 2, sy / 2, sz / 2)
    .map((c) => [cx + c[0], cy + c[1], cz + c[2]]);
  return QUADS.map((q, i) => ({
    pts: q.map((k) => v[k]), fill: shadeHex(fill, QUAD_SHADE[i]), alpha: 1,
  }));
}

export function cylinderFaces(cx, cy, cz, r, hgt, fill, camAz, seg = 20) {
  const hz = hgt / 2;
  const faces = [];
  const ring = [];
  for (let i = 0; i < seg; i++) {
    const a = (i / seg) * Math.PI * 2;
    ring.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
  }
  for (let i = 0; i < seg; i++) {
    const a = ring[i];
    const b = ring[(i + 1) % seg];
    // Shade by how squarely this wall faces the camera's azimuth.
    const mid = ((i + 0.5) / seg) * Math.PI * 2;
    const s = 0.55 + 0.45 * Math.max(0, Math.cos(mid - camAz - Math.PI));
    faces.push({
      pts: [[a[0], a[1], cz - hz], [b[0], b[1], cz - hz],
            [b[0], b[1], cz + hz], [a[0], a[1], cz + hz]],
      fill: shadeHex(fill, s), alpha: 1,
    });
  }
  faces.push({ pts: ring.map((a) => [a[0], a[1], cz + hz]),
               fill: shadeHex(fill, 1.05), alpha: 1 });
  return faces;
}

/// The vehicle at a pose: an oriented body box, four rotor discs and the arms.
///
/// Rotor positions come from scene.json (generated by scripts/gen_assets.py
/// from the same rotor_layout() that writes model.sdf), in mixer index order.
/// Recomputing them from the arm length here would be a second definition of
/// the airframe, and the overlay arrows index the same list -- so a drawn
/// rotor and its thrust arrow always belong together.
export function droneFaces(pose, drone) {
  if (!pose || !drone) return [];
  const M = quatMat(pose.q);
  const toWorld = (local) => add(pose.p, rotate(M, local));
  const [bx, by, bz] = drone.body;
  const faces = [];

  const v = boxCorners(bx / 2, by / 2, bz / 2).map(toWorld);
  QUADS.forEach((q, i) => faces.push({
    pts: q.map((k) => v[k]),
    fill: shadeHex("#3d4655", QUAD_SHADE[i] * 0.9),
    alpha: 1,
  }));

  const hubs = drone.rotors || [];
  for (const hub of hubs) {
    // Front pair red so heading is readable without hunting for an axis.
    const colour = hub[0] > 0 ? "#ef4444" : "#94a3b8";
    const ring = [];
    for (let i = 0; i < 14; i++) {
      const a = (i / 14) * Math.PI * 2;
      ring.push(toWorld([hub[0] + drone.rotor_radius * Math.cos(a),
                         hub[1] + drone.rotor_radius * Math.sin(a),
                         hub[2]]));
    }
    faces.push({ pts: ring, fill: colour, alpha: 0.92 });
    faces.push({
      pts: [toWorld([0, 0, 0]), toWorld([hub[0], hub[1], hub[2] - 0.012]),
            toWorld([hub[0], hub[1], hub[2] + 0.012])],
      fill: "#2b3240", alpha: 1,
    });
  }
  return faces;
}
