// Scene geometry as lists of faces. Pure: every function returns
// {pts:[worldPoint...], fill, alpha} and touches no canvas.
//
// Shading is crude on purpose -- a fixed brightness per face orientation, no
// light model. It is enough to read shape from, and a real one would be the
// first step towards carrying a 3D engine for a scene that is a grid, some
// cylinders and a drone.

import { add, quatMat, rotate } from "./vec3.js";

/// Multiply a #rrggbb hex colour by k, clamped. k > 1 brightens.
export function shadeHex(hex, k) {
  const n = parseInt(hex.slice(1), 16);
  const ch = (shift) => Math.min(255, Math.round(((n >> shift) & 255) * k));
  return `rgb(${ch(16)},${ch(8)},${ch(0)})`;
}

const QUADS = [[0, 1, 2, 3], [4, 5, 6, 7], [0, 1, 5, 4],
               [1, 2, 6, 5], [2, 3, 7, 6], [3, 0, 4, 7]];
const QUAD_SHADE = [0.55, 1.0, 0.78, 0.68, 0.78, 0.68];

function boxCorners(hx, hy, hz) {
  return [
    [-hx, -hy, -hz], [hx, -hy, -hz], [hx, hy, -hz], [-hx, hy, -hz],
    [-hx, -hy, hz], [hx, -hy, hz], [hx, hy, hz], [-hx, hy, hz],
  ];
}

export function boxFaces(cx, cy, cz, sx, sy, sz, fill) {
  const v = boxCorners(sx / 2, sy / 2, sz / 2)
    .map((c) => [cx + c[0], cy + c[1], cz + c[2]]);
  return QUADS.map((q, i) => ({
    pts: q.map((k) => v[k]), fill: shadeHex(fill, QUAD_SHADE[i]), alpha: 1,
  }));
}

export function cylinderFaces(cx, cy, cz, r, hgt, fill, camAz, seg = 20) {
  const hz = hgt / 2;
  const faces = [];
  const ring = [];
  for (let i = 0; i < seg; i++) {
    const a = (i / seg) * Math.PI * 2;
    ring.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
  }
  for (let i = 0; i < seg; i++) {
    const a = ring[i];
    const b = ring[(i + 1) % seg];
    // Shade by how squarely this wall faces the camera's azimuth.
    const mid = ((i + 0.5) / seg) * Math.PI * 2;
    const s = 0.55 + 0.45 * Math.max(0, Math.cos(mid - camAz - Math.PI));
    faces.push({
      pts: [[a[0], a[1], cz - hz], [b[0], b[1], cz - hz],
            [b[0], b[1], cz + hz], [a[0], a[1], cz + hz]],
      fill: shadeHex(fill, s), alpha: 1,
    });
  }
  faces.push({ pts: ring.map((a) => [a[0], a[1], cz + hz]),
               fill: shadeHex(fill, 1.05), alpha: 1 });
  return faces;
}

/// A sphere as latitude bands of quads. Translucent, because these are the
/// moving obstacles of a space-time scenario and the plan threads between
/// them: an opaque fence hides the path and the vehicle behind it.
/// Shaded by latitude (top bright) and by azimuth against the camera, the
/// same crude rule as the cylinder walls.
export function sphereFaces(cx, cy, cz, r, fill, camAz, seg = 14, bands = 7, alpha = 0.5) {
  const faces = [];
  const ring = (lat) => {
    const z = cz + r * Math.sin(lat);
    const rr = r * Math.cos(lat);
    const pts = [];
    for (let i = 0; i < seg; i++) {
      const a = (i / seg) * Math.PI * 2;
      pts.push([cx + rr * Math.cos(a), cy + rr * Math.sin(a), z]);
    }
    return pts;
  };
  for (let b = 0; b < bands; b++) {
    const lat0 = -Math.PI / 2 + (b / bands) * Math.PI;
    const lat1 = -Math.PI / 2 + ((b + 1) / bands) * Math.PI;
    const lo = ring(lat0);
    const hi = ring(lat1);
    const up = 0.6 + 0.4 * (b + 0.5) / bands;
    for (let i = 0; i < seg; i++) {
      const j = (i + 1) % seg;
      const mid = ((i + 0.5) / seg) * Math.PI * 2;
      const s = up * (0.7 + 0.3 * Math.max(0, Math.cos(mid - camAz - Math.PI)));
      faces.push({ pts: [lo[i], lo[j], hi[j], hi[i]], fill: shadeHex(fill, s), alpha });
    }
  }
  return faces;
}

/// The vehicle at a pose: an oriented body box, four rotor discs and the arms.
///
/// Rotor positions come from scene.json (generated by scripts/gen_assets.py
/// from the same rotor_layout() that writes model.sdf), in mixer index order.
/// Recomputing them from the arm length here would be a second definition of
/// the airframe, and the overlay arrows index the same list -- so a drawn
/// rotor and its thrust arrow always belong together.
export function droneFaces(pose, drone) {
  if (!pose || !drone) return [];
  const M = quatMat(pose.q);
  const toWorld = (local) => add(pose.p, rotate(M, local));
  const [bx, by, bz] = drone.body;
  const faces = [];

  const v = boxCorners(bx / 2, by / 2, bz / 2).map(toWorld);
  QUADS.forEach((q, i) => faces.push({
    pts: q.map((k) => v[k]),
    fill: shadeHex("#3d4655", QUAD_SHADE[i] * 0.9),
    alpha: 1,
  }));

  const hubs = drone.rotors || [];
  for (const hub of hubs) {
    // Front pair red so heading is readable without hunting for an axis.
    const colour = hub[0] > 0 ? "#ef4444" : "#94a3b8";
    const ring = [];
    for (let i = 0; i < 14; i++) {
      const a = (i / 14) * Math.PI * 2;
      ring.push(toWorld([hub[0] + drone.rotor_radius * Math.cos(a),
                         hub[1] + drone.rotor_radius * Math.sin(a),
                         hub[2]]));
    }
    faces.push({ pts: ring, fill: colour, alpha: 0.92 });
    faces.push({
      pts: [toWorld([0, 0, 0]), toWorld([hub[0], hub[1], hub[2] - 0.012]),
            toWorld([hub[0], hub[1], hub[2] + 0.012])],
      fill: "#2b3240", alpha: 1,
    });
  }
  return faces;
}

/// The obstacles the referee says exist RIGHT NOW, as faces.
///
/// Drawn from the referee's report rather than from scene.json, because the
/// report is the only account of where they are: they are not Gazebo bodies,
/// their centres follow Bezier curves, and outside its window an obstacle is
/// ABSENT rather than parked somewhere. An inactive one is skipped entirely --
/// drawing a ghost would say the vehicle is threading a gap that is not there.
///
/// A "column" is a disc at every altitude, which is what an obstacle from a
/// scenario planned in two spatial dimensions is. It is drawn as a tall
/// cylinder because a disc at every altitude has no top to draw.
export function obstacleFaces(clearance, colors, camAz, columnHeight = 6) {
  const faces = [];
  if (!clearance || !clearance.obstacles) return faces;
  for (const o of clearance.obstacles) {
    if (!o.active) continue;
    const [x, y, z] = o.pos;
    const fill = (colors && colors[o.name]) || "#e67e22";
    faces.push(...(o.type === "column"
      ? cylinderFaces(x, y, columnHeight / 2, o.r, columnHeight, fill, camAz)
      : sphereFaces(x, y, z, o.r, fill, camAz)));
  }
  return faces;
}

/// Every analytic hit as a red three-axis cross at the vehicle position it
/// The sight lines a scenario's stations need kept clear, as segments.
///
/// Drawn from the referee's own report, like the obstacles: it is the only
/// thing that knows where the stations are and whether the line is clear right
/// now. A blocked line is drawn in the bad colour, which is the whole point --
/// the vehicle can be nowhere near an obstacle and still be behind it, and
/// that failure is invisible in a picture of clearances.
export function sightLines(clearance, pose, colours = {}) {
  const out = [];
  if (!clearance || !pose || !clearance.stations || !clearance.stations.length) return out;
  const blocked = clearance.los_margin_m !== null && clearance.los_margin_m < 0;
  for (const st of clearance.stations) {
    out.push({
      a: st.slice(),
      b: pose.p.slice(),
      colour: blocked ? (colours.blocked || "#f87171") : (colours.clear || "#34d399"),
      width: blocked ? 2 : 1,
    });
  }
  return out;
}

/// A station: a small pad on the ground with a mast, so it reads as a place
/// rather than as another obstacle.
export function stationFaces(clearance, colour = "#8b93a7") {
  const faces = [];
  if (!clearance || !clearance.stations) return faces;
  const r = 0.6, h = 1.2, n = 8;
  for (const st of clearance.stations) {
    const ring = [];
    for (let i = 0; i < n; i++) {
      const a = (2 * Math.PI * i) / n;
      ring.push([st[0] + r * Math.cos(a), st[1] + r * Math.sin(a), st[2]]);
    }
    faces.push({ pts: ring, colour, kind: "station" });
    for (let i = 0; i < n; i++) {
      const j = (i + 1) % n;
      faces.push({
        pts: [ring[i], ring[j], [st[0], st[1], st[2] + h]],
        colour,
        kind: "station",
      });
    }
  }
  return faces;
}

/// happened at, plus a drop line to the ground so the spot reads in 3D.
/// The cross is sized to the vehicle radius: it marks where the ENVELOPE
/// was when it went in, which is the thing the referee measures.
export function hitMarkers(clearance, radius = 0.3) {
  const segs = [];
  if (!clearance || !clearance.hits) return segs;
  const red = "rgba(239,68,68,.95)";
  for (const h of clearance.hits) {
    const [x, y, z] = h.pos;
    segs.push({ a: [x - radius, y, z], b: [x + radius, y, z], colour: red });
    segs.push({ a: [x, y - radius, z], b: [x, y + radius, z], colour: red });
    segs.push({ a: [x, y, z - radius], b: [x, y, z + radius], colour: red });
    segs.push({ a: [x, y, 0.005], b: [x, y, z], colour: "rgba(239,68,68,.35)" });
  }
  return segs;
}
