<?xml version="1.0"?>
<package format="3">
  <name>dsim_description</name>
  <version>0.1.0</version>
  <description>quadrotor Gazebo model.</description>
  <maintainer email="banana99ou@gmail.com">JHY</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
